# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0023_auto_20190418_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2providerconfig',
            name='auth_url',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Authentication URL'),
        ),
        migrations.AddField(
            model_name='oauth2providerconfig',
            name='redirect_uri',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Redirect URL'),
        ),
        migrations.AddField(
            model_name='oauth2providerconfig',
            name='token_url',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'Token URL'),
        ),
        migrations.AddField(
            model_name='oauth2providerconfig',
            name='user_info_url',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'User Info URL'),
        ),
    ]
